name: .CI Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore src/Iti.Backend.Challenge.sln
    - name: Build
      run: dotnet build src/Iti.Backend.Challenge.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test src/Iti.Backend.Challenge.sln -v n
